# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

matches:
  # общие замены, сначала - общесистемные
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":list"
    doc: Показать список клавиатурных расширений
    replace: "espanso match list"

  - trigger: ":doc"
    doc: Показать краткую памятку по команде
    replace: "python3 {{ help_path }}/user/show_doc.py [userfile] cmd | glow -"
    vars:
      - name: help_path
        type: shell
        params:
          cmd: "espanso path | grep Config | cut -d : -f 2"

  - trigger: ":help"
    doc: 
      - Вывести файл с подсказкой по espanso
    replace: "glow {{ help_path }}/user/help.md"
    vars:
      - name: help_path
        type: shell
        params:
          cmd: "espanso path | grep Config | cut -d : -f 2"

  - trigger: ":shmods"
    doc: 
      - Показать список пользовательских файлов
      - и их включенность (атрибут parent должен указывать на default)
    replace: "grep -H parent `espanso path | grep Config | cut -d : -f 2`/user/*.yml"

  # дальше пошли просто замены
  - trigger: ":gmm"
    replace: "korolmi@gmail.com"

  - trigger: ":mkk"
    replace: "Mikhail Korolev"

  - trigger: ":ph"
    replace: "89030034499"

  - trigger: ":свв"
    replace: "С уважением"

  - trigger: ":мхх"
    replace: "Михаил"

  # подстановки для маркдауна, ноутбуков и т.п., технические

  - trigger: ":х1"
    replace: "# "

  - trigger: ":х2"
    replace: "## "

  - trigger: ":х3"
    replace: "### "

  - trigger: ":юн"
    replace: "Jupyter Notebook"

  - trigger: ":кд"
    replace: "<code>$|$</code>"

  - trigger: ":сст"
    replace: "<syntaxhighlight lang=\"python\">>>> "

  - trigger: ":ссе"
    replace: "</syntaxhighlight>"

  # предметная область программирования и питона

  - trigger: ":сп"
    replace: "spark"
    propagate_case: true

  - trigger: ":аг"
    replace: "agile"
    propagate_case: true

  - trigger: ":лн"
    replace: "learning"
    propagate_case: true

  - trigger: ":пи"
    replace: "python"
    propagate_case: true

  - trigger: ":вш"
    replace: "workshop"
    propagate_case: true

  - trigger: ":ли"
    replace: "linux"
    propagate_case: true

  - trigger: ":вф"
    replace: "workflow"

  - trigger: ":дф"
    replace: "dataflow"

  - trigger: ":гп"
    replace: "GreenPlum"

  - trigger: ":пг"
    replace: "PostgreSQL"

  - trigger: ":нф"
    replace: "NiFi"

  - trigger: ":фф"
    replace: "FlowFile"

  - trigger: ":дж"
    replace: "django"

  - trigger: ":ака"
    replace: "Agile Coding Academy"

  - trigger: ":хк"
    replace: "<!-- $|$ -->"
